#### Exercise 1: NumPy: Create an array with values ranging from 12 to 38

In [1]:
import numpy as np

num_array = np.arange(12,38,1)

num_array

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

#### Exercise 2: Add a border around an existing array

In [2]:
num_identity_matrix = np.ones((3,3))

np.pad(num_identity_matrix, pad_width=1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### Exercise 3: Convert a list and tuple into arrays

In [3]:
list = [1,2,3,4,5,6,7,8]

print("List to array:")
print(np.array(list))

tuple = (8,4,6,1,2,3)

print("Tuple to array")
print(np.array(tuple).reshape(2,3))

List to array:
[1 2 3 4 5 6 7 8]
Tuple to array
[[8 4 6]
 [1 2 3]]


In [4]:
#  trying np.asaray 

print(np.asarray(list))

print(np.asarray(tuple).reshape(2,3))

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


#### Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degree

In [5]:
farh_values = [0, 12, 45.21, 34, 99.91]

farh_values = np.asarray(farh_values)

print(farh_values)

# convert centigrade to farhenheit

print(" Values in centigrade degrees")

# (32°F − 32) × 5/9

print((farh_values - 32) * (5/9))

[ 0.   12.   45.21 34.   99.91]
 Values in centigrade degrees
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


#### Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [6]:
numpy_array = np.array([1,2,3])

print("size of the array", numpy_array.size)
print("Length of one array element in bytes", numpy_array.itemsize)
print("Total bytes consumed by the elements of the array", numpy_array.nbytes)

size of the array 3
Length of one array element in bytes 4
Total bytes consumed by the elements of the array 12


#### Exercise 6: Get the unique elements of an array

In [7]:
numpy_orig_array = np.array([10,10,20,20,30,30])

print("unique elements of the above array")
print(np.unique(numpy_orig_array))

np_2d_array = np.array([[1,1],[2,3]])

print("unique elements of the above 2D array")
print(np.unique(np_2d_array))

unique elements of the above array
[10 20 30]
unique elements of the above 2D array
[1 2 3]


####  Exercise 7: Change the dimension of an array

In [8]:
array_1d = np.arange(1,10,1)

print("original array", array_1d)

array_2d = array_1d.reshape(3,3)
print("reshaped 3 x 3 array")
print(array_2d)

original array [1 2 3 4 5 6 7 8 9]
reshaped 3 x 3 array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [9]:
lin_space_array = np.linspace(2.5,6.5,30)

print(lin_space_array)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


#### Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [10]:
arr_1 = np.array([10,20,30])
arr_2 = np.array([40,50,60])

np.column_stack([arr_1, arr_2])


array([[10, 40],
       [20, 50],
       [30, 60]])

#### Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [11]:
np_arr = np.zeros((5,5))

print("original array")
print(np_arr)

rows = 5
cols = 5

print("updated array")
for i in range(rows):
    for j in range(cols):
        np_arr[i,j] = j

print(np_arr)

original array
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
updated array
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [12]:
np_mul_3 = np.arange(3,100,step=3)
print("Multiples of 3 array")
print(np_mul_3)
print("----")
np_mul_5 = np.arange(5,100,step=5)
print("Multiples of 5 array")
print(np_mul_5)

np_mul_3_5 = np.concatenate([np_mul_3,np_mul_5])
print("---")
print("multiples of 3 and 5 array")
print(np.sort(np_mul_3_5))

print("---")
print("sum of multiples of 3 and 5 is", np.sum(np.unique(np_mul_3_5)))

Multiples of 3 array
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
----
Multiples of 5 array
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
---
multiples of 3 and 5 array
[ 3  5  6  9 10 12 15 15 18 20 21 24 25 27 30 30 33 35 36 39 40 42 45 45
 48 50 51 54 55 57 60 60 63 65 66 69 70 72 75 75 78 80 81 84 85 87 90 90
 93 95 96 99]
---
sum of multiples of 3 and 5 is 2318


#### Exercise 12: Combine a one and a two dimensional array together and display their elements

In [13]:
np_1d = np.arange(0,4)
print(np_1d)
print("---")

np_2d = np.arange(0,8).reshape(2,4)
print(np_2d)
print("---")

for a,b in np.nditer([np_1d,np_2d]):
    print(a,":",b)

[0 1 2 3]
---
[[0 1 2 3]
 [4 5 6 7]]
---
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


#### Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [14]:
org_array = np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])

# Replace all the elements of org_array
# condition: anything greater than 0.5, replace with .5

filter_arr = org_array > 0.5

org_array[filter_arr] = 0.5

print("---")

print(org_array)

---
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


#### Exercise 14: Add a new row to an empty numpy array

In [15]:
empty_arr = np.empty((0,3), int)
print("empty_arr")
print(empty_arr)

first_arr = np.array([10,20,30])
second_arr = np.array([40,50,60])

empty_arr = np.append(empty_arr,[first_arr, second_arr],axis=0)
print("New array:\n",empty_arr)

empty_arr
[]
New array:
 [[10 20 30]
 [40 50 60]]


#### Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis

In [173]:
np_arr1 = np.array([1,2,3])
np_arr2 = np.array([2,3,4])

print(np.vstack([np_arr1, np_arr2]))
print("---")
np_arr3 = np.array([[1],[2],[3]])
np_arr4 = np.array([[2],[3],[4]])

print(np.vstack([np_arr3, np_arr4]))

[[1 2 3]
 [2 3 4]]
---
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
